"""change table name

Revision ID: 382f6011c095
Revises: d4f2cbda8a0c
Create Date: 2020-02-11 01:15:48.869875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382f6011c095'
down_revision = 'd4f2cbda8a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laundry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('item_type', sa.String(length=10), nullable=True),
    sa.Column('item_size', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laundry_barcode'), 'laundry', ['barcode'], unique=False)
    op.create_index(op.f('ix_laundry_item_size'), 'laundry', ['item_size'], unique=False)
    op.create_index(op.f('ix_laundry_item_type'), 'laundry', ['item_type'], unique=False)
    op.drop_index('ix_outgoing_barcode', table_name='outgoing')
    op.drop_index('ix_outgoing_item_size', table_name='outgoing')
    op.drop_index('ix_outgoing_item_type', table_name='outgoing')
    op.drop_table('outgoing')
    op.drop_constraint(None, 'status', type_='foreignkey')
    op.create_foreign_key(None, 'status', 'laundry', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'status', type_='foreignkey')
    op.create_foreign_key(None, 'status', 'outgoing', ['item_id'], ['id'])
    op.create_table('outgoing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('item_size', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outgoing_item_type', 'outgoing', ['item_type'], unique=False)
    op.create_index('ix_outgoing_item_size', 'outgoing', ['item_size'], unique=False)
    op.create_index('ix_outgoing_barcode', 'outgoing', ['barcode'], unique=False)
    op.drop_index(op.f('ix_laundry_item_type'), table_name='laundry')
    op.drop_index(op.f('ix_laundry_item_size'), table_name='laundry')
    op.drop_index(op.f('ix_laundry_barcode'), table_name='laundry')
    op.drop_table('laundry')
    # ### end Alembic commands ###
