"""empty message

Revision ID: 3f35b496e40d
Revises: 6f8b31bb8824
Create Date: 2020-03-01 20:07:15.408330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f35b496e40d'
down_revision = '6f8b31bb8824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timestamp', sa.Column('item_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'timestamp', 'laundry', ['item_id'], ['id'])
    op.drop_index(op.f('ix_timestamp_barcode'), table_name='timestamp')
    op.drop_column('timestamp', 'barcode')
    # ### end Alembic commands ###
