"""empty message

Revision ID: 709955ee8a07
Revises: 3f35b496e40d
Create Date: 2020-03-01 20:33:28.849774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709955ee8a07'
down_revision = '3f35b496e40d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_barcode'), 'time', ['barcode'], unique=False)
    op.create_index(op.f('ix_time_status'), 'time', ['status'], unique=False)
    op.create_index(op.f('ix_time_timestamp'), 'time', ['timestamp'], unique=False)
    op.drop_index('ix_timestamp_barcode', table_name='timestamp')
    op.drop_index('ix_timestamp_status', table_name='timestamp')
    op.drop_index('ix_timestamp_timestamp', table_name='timestamp')
    op.drop_table('timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timestamp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('barcode', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['laundry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timestamp_timestamp', 'timestamp', ['timestamp'], unique=False)
    op.create_index('ix_timestamp_status', 'timestamp', ['status'], unique=False)
    op.create_index('ix_timestamp_barcode', 'timestamp', ['barcode'], unique=False)
    op.drop_index(op.f('ix_time_timestamp'), table_name='time')
    op.drop_index(op.f('ix_time_status'), table_name='time')
    op.drop_index(op.f('ix_time_barcode'), table_name='time')
    op.drop_table('time')
    # ### end Alembic commands ###
