"""update search table

Revision ID: 7910158e2556
Revises: d8082e3bbd41
Create Date: 2020-02-18 04:23:20.129226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7910158e2556'
down_revision = 'd8082e3bbd41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('item_note', sa.String(length=20), nullable=True))
    op.add_column('search', sa.Column('item_size', sa.String(length=10), nullable=True))
    op.add_column('search', sa.Column('item_type', sa.String(length=10), nullable=True))
    op.add_column('search', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_search_item_note'), 'search', ['item_note'], unique=False)
    op.create_index(op.f('ix_search_item_size'), 'search', ['item_size'], unique=False)
    op.create_index(op.f('ix_search_item_type'), 'search', ['item_type'], unique=False)
    op.create_index(op.f('ix_search_status'), 'search', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_status'), table_name='search')
    op.drop_index(op.f('ix_search_item_type'), table_name='search')
    op.drop_index(op.f('ix_search_item_size'), table_name='search')
    op.drop_index(op.f('ix_search_item_note'), table_name='search')
    op.drop_column('search', 'status')
    op.drop_column('search', 'item_type')
    op.drop_column('search', 'item_size')
    op.drop_column('search', 'item_note')
    # ### end Alembic commands ###
