"""init table

Revision ID: 7d342ea9a24f
Revises: 
Create Date: 2020-02-16 03:13:22.401180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d342ea9a24f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laundry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('item_type', sa.String(length=10), nullable=True),
    sa.Column('item_size', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laundry_barcode'), 'laundry', ['barcode'], unique=False)
    op.create_index(op.f('ix_laundry_item_size'), 'laundry', ['item_size'], unique=False)
    op.create_index(op.f('ix_laundry_item_type'), 'laundry', ['item_type'], unique=False)
    op.create_index(op.f('ix_laundry_status'), 'laundry', ['status'], unique=False)
    op.create_table('timestamp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['laundry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timestamp_timestamp'), 'timestamp', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timestamp_timestamp'), table_name='timestamp')
    op.drop_table('timestamp')
    op.drop_index(op.f('ix_laundry_status'), table_name='laundry')
    op.drop_index(op.f('ix_laundry_item_type'), table_name='laundry')
    op.drop_index(op.f('ix_laundry_item_size'), table_name='laundry')
    op.drop_index(op.f('ix_laundry_barcode'), table_name='laundry')
    op.drop_table('laundry')
    # ### end Alembic commands ###
