"""add notes to item

Revision ID: 875f5a2580f2
Revises: 7d342ea9a24f
Create Date: 2020-02-16 03:16:34.469595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875f5a2580f2'
down_revision = '7d342ea9a24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laundry', sa.Column('item_note', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_laundry_item_note'), 'laundry', ['item_note'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laundry_item_note'), table_name='laundry')
    op.drop_column('laundry', 'item_note')
    # ### end Alembic commands ###
