"""users table

Revision ID: 9b3c0d2b4785
Revises: 
Create Date: 2020-02-04 05:00:00.936767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3c0d2b4785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outgoing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('item_type', sa.String(length=10), nullable=True),
    sa.Column('item_size', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outgoing_barcode'), 'outgoing', ['barcode'], unique=False)
    op.create_index(op.f('ix_outgoing_item_size'), 'outgoing', ['item_size'], unique=False)
    op.create_index(op.f('ix_outgoing_item_type'), 'outgoing', ['item_type'], unique=False)
    op.create_index(op.f('ix_outgoing_timestamp'), 'outgoing', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outgoing_timestamp'), table_name='outgoing')
    op.drop_index(op.f('ix_outgoing_item_type'), table_name='outgoing')
    op.drop_index(op.f('ix_outgoing_item_size'), table_name='outgoing')
    op.drop_index(op.f('ix_outgoing_barcode'), table_name='outgoing')
    op.drop_table('outgoing')
    # ### end Alembic commands ###
