"""empty message

Revision ID: d4f2cbda8a0c
Revises: 
Create Date: 2020-02-05 02:24:14.470299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f2cbda8a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outgoing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.Column('item_type', sa.String(length=10), nullable=True),
    sa.Column('item_size', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outgoing_barcode'), 'outgoing', ['barcode'], unique=False)
    op.create_index(op.f('ix_outgoing_item_size'), 'outgoing', ['item_size'], unique=False)
    op.create_index(op.f('ix_outgoing_item_type'), 'outgoing', ['item_type'], unique=False)
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['outgoing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_status'), 'status', ['status'], unique=False)
    op.create_index(op.f('ix_status_timestamp'), 'status', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_timestamp'), table_name='status')
    op.drop_index(op.f('ix_status_status'), table_name='status')
    op.drop_table('status')
    op.drop_index(op.f('ix_outgoing_item_type'), table_name='outgoing')
    op.drop_index(op.f('ix_outgoing_item_size'), table_name='outgoing')
    op.drop_index(op.f('ix_outgoing_barcode'), table_name='outgoing')
    op.drop_table('outgoing')
    # ### end Alembic commands ###
