"""empty message

Revision ID: d8082e3bbd41
Revises: 875f5a2580f2
Create Date: 2020-02-17 22:15:34.706919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8082e3bbd41'
down_revision = '875f5a2580f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_barcode'), 'search', ['barcode'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_barcode'), table_name='search')
    op.drop_table('search')
    # ### end Alembic commands ###
