"""items table

Revision ID: e5314daeb4fd
Revises: 9b3c0d2b4785
Create Date: 2020-02-04 05:18:18.779838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5314daeb4fd'
down_revision = '9b3c0d2b4785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outgoing_status'), 'outgoing', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outgoing_status'), table_name='outgoing')
    # ### end Alembic commands ###
